name: CD

on:
  push:
    branches: [ production ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PUSH_TOKEN }}
    - name: Deploy to production
      uses: appleboy/ssh-action@master
      with:
        username: streams
        host: 68.183.132.200
        password: ${{ secrets.SSH_PASSWORD }}
        script: 'cd /home/streams && ./server_deploy.sh'
